[package]
name = "forwarder"
version = "0.1.0"
authors = ["thesinglecloud <hanfeng@zdns.cn>"]
edition = "2018"
publish = false

[dependencies]
tokio = "0.1.8"
futures = "0.1.24"
r53 = { git = "https://github.com/zdnscloud/r53"}
server = { path = "../server" }
