// This file is generated by rust-protobuf 2.7.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `dynamic_update_interface.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_7_0;

#[derive(PartialEq,Clone,Default)]
pub struct AddRRsetRequest {
    // message fields
    pub zone: ::std::string::String,
    pub rrsets: ::protobuf::RepeatedField<super::rrset::RRset>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AddRRsetRequest {
    fn default() -> &'a AddRRsetRequest {
        <AddRRsetRequest as ::protobuf::Message>::default_instance()
    }
}

impl AddRRsetRequest {
    pub fn new() -> AddRRsetRequest {
        ::std::default::Default::default()
    }

    // string zone = 1;


    pub fn get_zone(&self) -> &str {
        &self.zone
    }
    pub fn clear_zone(&mut self) {
        self.zone.clear();
    }

    // Param is passed by value, moved
    pub fn set_zone(&mut self, v: ::std::string::String) {
        self.zone = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zone(&mut self) -> &mut ::std::string::String {
        &mut self.zone
    }

    // Take field
    pub fn take_zone(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.zone, ::std::string::String::new())
    }

    // repeated .client.RRset rrsets = 2;


    pub fn get_rrsets(&self) -> &[super::rrset::RRset] {
        &self.rrsets
    }
    pub fn clear_rrsets(&mut self) {
        self.rrsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_rrsets(&mut self, v: ::protobuf::RepeatedField<super::rrset::RRset>) {
        self.rrsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_rrsets(&mut self) -> &mut ::protobuf::RepeatedField<super::rrset::RRset> {
        &mut self.rrsets
    }

    // Take field
    pub fn take_rrsets(&mut self) -> ::protobuf::RepeatedField<super::rrset::RRset> {
        ::std::mem::replace(&mut self.rrsets, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for AddRRsetRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.rrsets {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.zone)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.rrsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.zone.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.zone);
        }
        for value in &self.rrsets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.zone.is_empty() {
            os.write_string(1, &self.zone)?;
        }
        for v in &self.rrsets {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AddRRsetRequest {
        AddRRsetRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "zone",
                    |m: &AddRRsetRequest| { &m.zone },
                    |m: &mut AddRRsetRequest| { &mut m.zone },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::rrset::RRset>>(
                    "rrsets",
                    |m: &AddRRsetRequest| { &m.rrsets },
                    |m: &mut AddRRsetRequest| { &mut m.rrsets },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<AddRRsetRequest>(
                    "AddRRsetRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AddRRsetRequest {
        static mut instance: ::protobuf::lazy::Lazy<AddRRsetRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AddRRsetRequest,
        };
        unsafe {
            instance.get(AddRRsetRequest::new)
        }
    }
}

impl ::protobuf::Clear for AddRRsetRequest {
    fn clear(&mut self) {
        self.zone.clear();
        self.rrsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AddRRsetRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddRRsetRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct AddRRsetResponse {
    // message fields
    pub code: StatusCode,
    pub message: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AddRRsetResponse {
    fn default() -> &'a AddRRsetResponse {
        <AddRRsetResponse as ::protobuf::Message>::default_instance()
    }
}

impl AddRRsetResponse {
    pub fn new() -> AddRRsetResponse {
        ::std::default::Default::default()
    }

    // .client.StatusCode code = 1;


    pub fn get_code(&self) -> StatusCode {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = StatusCode::Succeed;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: StatusCode) {
        self.code = v;
    }

    // string message = 2;


    pub fn get_message(&self) -> &str {
        &self.message
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        &mut self.message
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.message, ::std::string::String::new())
    }
}

impl ::protobuf::Message for AddRRsetResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.message)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != StatusCode::Succeed {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.code != StatusCode::Succeed {
            os.write_enum(1, self.code.value())?;
        }
        if !self.message.is_empty() {
            os.write_string(2, &self.message)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AddRRsetResponse {
        AddRRsetResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StatusCode>>(
                    "code",
                    |m: &AddRRsetResponse| { &m.code },
                    |m: &mut AddRRsetResponse| { &mut m.code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "message",
                    |m: &AddRRsetResponse| { &m.message },
                    |m: &mut AddRRsetResponse| { &mut m.message },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<AddRRsetResponse>(
                    "AddRRsetResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static AddRRsetResponse {
        static mut instance: ::protobuf::lazy::Lazy<AddRRsetResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const AddRRsetResponse,
        };
        unsafe {
            instance.get(AddRRsetResponse::new)
        }
    }
}

impl ::protobuf::Clear for AddRRsetResponse {
    fn clear(&mut self) {
        self.code = StatusCode::Succeed;
        self.message.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AddRRsetResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AddRRsetResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteDomainRequest {
    // message fields
    pub zone: ::std::string::String,
    pub names: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteDomainRequest {
    fn default() -> &'a DeleteDomainRequest {
        <DeleteDomainRequest as ::protobuf::Message>::default_instance()
    }
}

impl DeleteDomainRequest {
    pub fn new() -> DeleteDomainRequest {
        ::std::default::Default::default()
    }

    // string zone = 1;


    pub fn get_zone(&self) -> &str {
        &self.zone
    }
    pub fn clear_zone(&mut self) {
        self.zone.clear();
    }

    // Param is passed by value, moved
    pub fn set_zone(&mut self, v: ::std::string::String) {
        self.zone = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zone(&mut self) -> &mut ::std::string::String {
        &mut self.zone
    }

    // Take field
    pub fn take_zone(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.zone, ::std::string::String::new())
    }

    // repeated string names = 2;


    pub fn get_names(&self) -> &[::std::string::String] {
        &self.names
    }
    pub fn clear_names(&mut self) {
        self.names.clear();
    }

    // Param is passed by value, moved
    pub fn set_names(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.names = v;
    }

    // Mutable pointer to the field.
    pub fn mut_names(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.names
    }

    // Take field
    pub fn take_names(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.names, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for DeleteDomainRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.zone)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.names)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.zone.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.zone);
        }
        for value in &self.names {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.zone.is_empty() {
            os.write_string(1, &self.zone)?;
        }
        for v in &self.names {
            os.write_string(2, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteDomainRequest {
        DeleteDomainRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "zone",
                    |m: &DeleteDomainRequest| { &m.zone },
                    |m: &mut DeleteDomainRequest| { &mut m.zone },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "names",
                    |m: &DeleteDomainRequest| { &m.names },
                    |m: &mut DeleteDomainRequest| { &mut m.names },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteDomainRequest>(
                    "DeleteDomainRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteDomainRequest {
        static mut instance: ::protobuf::lazy::Lazy<DeleteDomainRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteDomainRequest,
        };
        unsafe {
            instance.get(DeleteDomainRequest::new)
        }
    }
}

impl ::protobuf::Clear for DeleteDomainRequest {
    fn clear(&mut self) {
        self.zone.clear();
        self.names.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteDomainRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteDomainRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteDomainResponse {
    // message fields
    pub code: StatusCode,
    pub message: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteDomainResponse {
    fn default() -> &'a DeleteDomainResponse {
        <DeleteDomainResponse as ::protobuf::Message>::default_instance()
    }
}

impl DeleteDomainResponse {
    pub fn new() -> DeleteDomainResponse {
        ::std::default::Default::default()
    }

    // .client.StatusCode code = 1;


    pub fn get_code(&self) -> StatusCode {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = StatusCode::Succeed;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: StatusCode) {
        self.code = v;
    }

    // string message = 2;


    pub fn get_message(&self) -> &str {
        &self.message
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        &mut self.message
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.message, ::std::string::String::new())
    }
}

impl ::protobuf::Message for DeleteDomainResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.message)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != StatusCode::Succeed {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.code != StatusCode::Succeed {
            os.write_enum(1, self.code.value())?;
        }
        if !self.message.is_empty() {
            os.write_string(2, &self.message)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteDomainResponse {
        DeleteDomainResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StatusCode>>(
                    "code",
                    |m: &DeleteDomainResponse| { &m.code },
                    |m: &mut DeleteDomainResponse| { &mut m.code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "message",
                    |m: &DeleteDomainResponse| { &m.message },
                    |m: &mut DeleteDomainResponse| { &mut m.message },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteDomainResponse>(
                    "DeleteDomainResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteDomainResponse {
        static mut instance: ::protobuf::lazy::Lazy<DeleteDomainResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteDomainResponse,
        };
        unsafe {
            instance.get(DeleteDomainResponse::new)
        }
    }
}

impl ::protobuf::Clear for DeleteDomainResponse {
    fn clear(&mut self) {
        self.code = StatusCode::Succeed;
        self.message.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteDomainResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteDomainResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteRRsetRequest {
    // message fields
    pub zone: ::std::string::String,
    pub rrsets: ::protobuf::RepeatedField<super::rrset::RRsetHeader>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteRRsetRequest {
    fn default() -> &'a DeleteRRsetRequest {
        <DeleteRRsetRequest as ::protobuf::Message>::default_instance()
    }
}

impl DeleteRRsetRequest {
    pub fn new() -> DeleteRRsetRequest {
        ::std::default::Default::default()
    }

    // string zone = 1;


    pub fn get_zone(&self) -> &str {
        &self.zone
    }
    pub fn clear_zone(&mut self) {
        self.zone.clear();
    }

    // Param is passed by value, moved
    pub fn set_zone(&mut self, v: ::std::string::String) {
        self.zone = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zone(&mut self) -> &mut ::std::string::String {
        &mut self.zone
    }

    // Take field
    pub fn take_zone(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.zone, ::std::string::String::new())
    }

    // repeated .client.RRsetHeader rrsets = 2;


    pub fn get_rrsets(&self) -> &[super::rrset::RRsetHeader] {
        &self.rrsets
    }
    pub fn clear_rrsets(&mut self) {
        self.rrsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_rrsets(&mut self, v: ::protobuf::RepeatedField<super::rrset::RRsetHeader>) {
        self.rrsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_rrsets(&mut self) -> &mut ::protobuf::RepeatedField<super::rrset::RRsetHeader> {
        &mut self.rrsets
    }

    // Take field
    pub fn take_rrsets(&mut self) -> ::protobuf::RepeatedField<super::rrset::RRsetHeader> {
        ::std::mem::replace(&mut self.rrsets, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for DeleteRRsetRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.rrsets {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.zone)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.rrsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.zone.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.zone);
        }
        for value in &self.rrsets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.zone.is_empty() {
            os.write_string(1, &self.zone)?;
        }
        for v in &self.rrsets {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteRRsetRequest {
        DeleteRRsetRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "zone",
                    |m: &DeleteRRsetRequest| { &m.zone },
                    |m: &mut DeleteRRsetRequest| { &mut m.zone },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::rrset::RRsetHeader>>(
                    "rrsets",
                    |m: &DeleteRRsetRequest| { &m.rrsets },
                    |m: &mut DeleteRRsetRequest| { &mut m.rrsets },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteRRsetRequest>(
                    "DeleteRRsetRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteRRsetRequest {
        static mut instance: ::protobuf::lazy::Lazy<DeleteRRsetRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteRRsetRequest,
        };
        unsafe {
            instance.get(DeleteRRsetRequest::new)
        }
    }
}

impl ::protobuf::Clear for DeleteRRsetRequest {
    fn clear(&mut self) {
        self.zone.clear();
        self.rrsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteRRsetRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteRRsetRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteRRsetResponse {
    // message fields
    pub code: StatusCode,
    pub message: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteRRsetResponse {
    fn default() -> &'a DeleteRRsetResponse {
        <DeleteRRsetResponse as ::protobuf::Message>::default_instance()
    }
}

impl DeleteRRsetResponse {
    pub fn new() -> DeleteRRsetResponse {
        ::std::default::Default::default()
    }

    // .client.StatusCode code = 1;


    pub fn get_code(&self) -> StatusCode {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = StatusCode::Succeed;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: StatusCode) {
        self.code = v;
    }

    // string message = 2;


    pub fn get_message(&self) -> &str {
        &self.message
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        &mut self.message
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.message, ::std::string::String::new())
    }
}

impl ::protobuf::Message for DeleteRRsetResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.message)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != StatusCode::Succeed {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.code != StatusCode::Succeed {
            os.write_enum(1, self.code.value())?;
        }
        if !self.message.is_empty() {
            os.write_string(2, &self.message)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteRRsetResponse {
        DeleteRRsetResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StatusCode>>(
                    "code",
                    |m: &DeleteRRsetResponse| { &m.code },
                    |m: &mut DeleteRRsetResponse| { &mut m.code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "message",
                    |m: &DeleteRRsetResponse| { &m.message },
                    |m: &mut DeleteRRsetResponse| { &mut m.message },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteRRsetResponse>(
                    "DeleteRRsetResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteRRsetResponse {
        static mut instance: ::protobuf::lazy::Lazy<DeleteRRsetResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteRRsetResponse,
        };
        unsafe {
            instance.get(DeleteRRsetResponse::new)
        }
    }
}

impl ::protobuf::Clear for DeleteRRsetResponse {
    fn clear(&mut self) {
        self.code = StatusCode::Succeed;
        self.message.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteRRsetResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteRRsetResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteRdataRequest {
    // message fields
    pub zone: ::std::string::String,
    pub rrsets: ::protobuf::RepeatedField<super::rrset::RRset>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteRdataRequest {
    fn default() -> &'a DeleteRdataRequest {
        <DeleteRdataRequest as ::protobuf::Message>::default_instance()
    }
}

impl DeleteRdataRequest {
    pub fn new() -> DeleteRdataRequest {
        ::std::default::Default::default()
    }

    // string zone = 1;


    pub fn get_zone(&self) -> &str {
        &self.zone
    }
    pub fn clear_zone(&mut self) {
        self.zone.clear();
    }

    // Param is passed by value, moved
    pub fn set_zone(&mut self, v: ::std::string::String) {
        self.zone = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zone(&mut self) -> &mut ::std::string::String {
        &mut self.zone
    }

    // Take field
    pub fn take_zone(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.zone, ::std::string::String::new())
    }

    // repeated .client.RRset rrsets = 2;


    pub fn get_rrsets(&self) -> &[super::rrset::RRset] {
        &self.rrsets
    }
    pub fn clear_rrsets(&mut self) {
        self.rrsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_rrsets(&mut self, v: ::protobuf::RepeatedField<super::rrset::RRset>) {
        self.rrsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_rrsets(&mut self) -> &mut ::protobuf::RepeatedField<super::rrset::RRset> {
        &mut self.rrsets
    }

    // Take field
    pub fn take_rrsets(&mut self) -> ::protobuf::RepeatedField<super::rrset::RRset> {
        ::std::mem::replace(&mut self.rrsets, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for DeleteRdataRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.rrsets {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.zone)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.rrsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.zone.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.zone);
        }
        for value in &self.rrsets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.zone.is_empty() {
            os.write_string(1, &self.zone)?;
        }
        for v in &self.rrsets {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteRdataRequest {
        DeleteRdataRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "zone",
                    |m: &DeleteRdataRequest| { &m.zone },
                    |m: &mut DeleteRdataRequest| { &mut m.zone },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::rrset::RRset>>(
                    "rrsets",
                    |m: &DeleteRdataRequest| { &m.rrsets },
                    |m: &mut DeleteRdataRequest| { &mut m.rrsets },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteRdataRequest>(
                    "DeleteRdataRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteRdataRequest {
        static mut instance: ::protobuf::lazy::Lazy<DeleteRdataRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteRdataRequest,
        };
        unsafe {
            instance.get(DeleteRdataRequest::new)
        }
    }
}

impl ::protobuf::Clear for DeleteRdataRequest {
    fn clear(&mut self) {
        self.zone.clear();
        self.rrsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteRdataRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteRdataRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DeleteRdataResponse {
    // message fields
    pub code: StatusCode,
    pub message: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DeleteRdataResponse {
    fn default() -> &'a DeleteRdataResponse {
        <DeleteRdataResponse as ::protobuf::Message>::default_instance()
    }
}

impl DeleteRdataResponse {
    pub fn new() -> DeleteRdataResponse {
        ::std::default::Default::default()
    }

    // .client.StatusCode code = 1;


    pub fn get_code(&self) -> StatusCode {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = StatusCode::Succeed;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: StatusCode) {
        self.code = v;
    }

    // string message = 2;


    pub fn get_message(&self) -> &str {
        &self.message
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        &mut self.message
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.message, ::std::string::String::new())
    }
}

impl ::protobuf::Message for DeleteRdataResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.message)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != StatusCode::Succeed {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.code != StatusCode::Succeed {
            os.write_enum(1, self.code.value())?;
        }
        if !self.message.is_empty() {
            os.write_string(2, &self.message)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DeleteRdataResponse {
        DeleteRdataResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StatusCode>>(
                    "code",
                    |m: &DeleteRdataResponse| { &m.code },
                    |m: &mut DeleteRdataResponse| { &mut m.code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "message",
                    |m: &DeleteRdataResponse| { &m.message },
                    |m: &mut DeleteRdataResponse| { &mut m.message },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<DeleteRdataResponse>(
                    "DeleteRdataResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DeleteRdataResponse {
        static mut instance: ::protobuf::lazy::Lazy<DeleteRdataResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const DeleteRdataResponse,
        };
        unsafe {
            instance.get(DeleteRdataResponse::new)
        }
    }
}

impl ::protobuf::Clear for DeleteRdataResponse {
    fn clear(&mut self) {
        self.code = StatusCode::Succeed;
        self.message.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DeleteRdataResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DeleteRdataResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UpdateRdataRequest {
    // message fields
    pub zone: ::std::string::String,
    pub old_rrsets: ::protobuf::RepeatedField<super::rrset::RRset>,
    pub new_rrsets: ::protobuf::RepeatedField<super::rrset::RRset>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UpdateRdataRequest {
    fn default() -> &'a UpdateRdataRequest {
        <UpdateRdataRequest as ::protobuf::Message>::default_instance()
    }
}

impl UpdateRdataRequest {
    pub fn new() -> UpdateRdataRequest {
        ::std::default::Default::default()
    }

    // string zone = 1;


    pub fn get_zone(&self) -> &str {
        &self.zone
    }
    pub fn clear_zone(&mut self) {
        self.zone.clear();
    }

    // Param is passed by value, moved
    pub fn set_zone(&mut self, v: ::std::string::String) {
        self.zone = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_zone(&mut self) -> &mut ::std::string::String {
        &mut self.zone
    }

    // Take field
    pub fn take_zone(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.zone, ::std::string::String::new())
    }

    // repeated .client.RRset old_rrsets = 2;


    pub fn get_old_rrsets(&self) -> &[super::rrset::RRset] {
        &self.old_rrsets
    }
    pub fn clear_old_rrsets(&mut self) {
        self.old_rrsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_old_rrsets(&mut self, v: ::protobuf::RepeatedField<super::rrset::RRset>) {
        self.old_rrsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_old_rrsets(&mut self) -> &mut ::protobuf::RepeatedField<super::rrset::RRset> {
        &mut self.old_rrsets
    }

    // Take field
    pub fn take_old_rrsets(&mut self) -> ::protobuf::RepeatedField<super::rrset::RRset> {
        ::std::mem::replace(&mut self.old_rrsets, ::protobuf::RepeatedField::new())
    }

    // repeated .client.RRset new_rrsets = 3;


    pub fn get_new_rrsets(&self) -> &[super::rrset::RRset] {
        &self.new_rrsets
    }
    pub fn clear_new_rrsets(&mut self) {
        self.new_rrsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_new_rrsets(&mut self, v: ::protobuf::RepeatedField<super::rrset::RRset>) {
        self.new_rrsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_new_rrsets(&mut self) -> &mut ::protobuf::RepeatedField<super::rrset::RRset> {
        &mut self.new_rrsets
    }

    // Take field
    pub fn take_new_rrsets(&mut self) -> ::protobuf::RepeatedField<super::rrset::RRset> {
        ::std::mem::replace(&mut self.new_rrsets, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for UpdateRdataRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.old_rrsets {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.new_rrsets {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.zone)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.old_rrsets)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.new_rrsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.zone.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.zone);
        }
        for value in &self.old_rrsets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        for value in &self.new_rrsets {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if !self.zone.is_empty() {
            os.write_string(1, &self.zone)?;
        }
        for v in &self.old_rrsets {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        for v in &self.new_rrsets {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpdateRdataRequest {
        UpdateRdataRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "zone",
                    |m: &UpdateRdataRequest| { &m.zone },
                    |m: &mut UpdateRdataRequest| { &mut m.zone },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::rrset::RRset>>(
                    "old_rrsets",
                    |m: &UpdateRdataRequest| { &m.old_rrsets },
                    |m: &mut UpdateRdataRequest| { &mut m.old_rrsets },
                ));
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::rrset::RRset>>(
                    "new_rrsets",
                    |m: &UpdateRdataRequest| { &m.new_rrsets },
                    |m: &mut UpdateRdataRequest| { &mut m.new_rrsets },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpdateRdataRequest>(
                    "UpdateRdataRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpdateRdataRequest {
        static mut instance: ::protobuf::lazy::Lazy<UpdateRdataRequest> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpdateRdataRequest,
        };
        unsafe {
            instance.get(UpdateRdataRequest::new)
        }
    }
}

impl ::protobuf::Clear for UpdateRdataRequest {
    fn clear(&mut self) {
        self.zone.clear();
        self.old_rrsets.clear();
        self.new_rrsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpdateRdataRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateRdataRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UpdateRdataResponse {
    // message fields
    pub code: StatusCode,
    pub message: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UpdateRdataResponse {
    fn default() -> &'a UpdateRdataResponse {
        <UpdateRdataResponse as ::protobuf::Message>::default_instance()
    }
}

impl UpdateRdataResponse {
    pub fn new() -> UpdateRdataResponse {
        ::std::default::Default::default()
    }

    // .client.StatusCode code = 1;


    pub fn get_code(&self) -> StatusCode {
        self.code
    }
    pub fn clear_code(&mut self) {
        self.code = StatusCode::Succeed;
    }

    // Param is passed by value, moved
    pub fn set_code(&mut self, v: StatusCode) {
        self.code = v;
    }

    // string message = 2;


    pub fn get_message(&self) -> &str {
        &self.message
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        &mut self.message
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.message, ::std::string::String::new())
    }
}

impl ::protobuf::Message for UpdateRdataResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.code, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.message)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.code != StatusCode::Succeed {
            my_size += ::protobuf::rt::enum_size(1, self.code);
        }
        if !self.message.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.message);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.code != StatusCode::Succeed {
            os.write_enum(1, self.code.value())?;
        }
        if !self.message.is_empty() {
            os.write_string(2, &self.message)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UpdateRdataResponse {
        UpdateRdataResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<StatusCode>>(
                    "code",
                    |m: &UpdateRdataResponse| { &m.code },
                    |m: &mut UpdateRdataResponse| { &mut m.code },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "message",
                    |m: &UpdateRdataResponse| { &m.message },
                    |m: &mut UpdateRdataResponse| { &mut m.message },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<UpdateRdataResponse>(
                    "UpdateRdataResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static UpdateRdataResponse {
        static mut instance: ::protobuf::lazy::Lazy<UpdateRdataResponse> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const UpdateRdataResponse,
        };
        unsafe {
            instance.get(UpdateRdataResponse::new)
        }
    }
}

impl ::protobuf::Clear for UpdateRdataResponse {
    fn clear(&mut self) {
        self.code = StatusCode::Succeed;
        self.message.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UpdateRdataResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UpdateRdataResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum StatusCode {
    Succeed = 0,
    Failed = 1,
    Unauthorized = 2,
    NotFound = 3,
}

impl ::protobuf::ProtobufEnum for StatusCode {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<StatusCode> {
        match value {
            0 => ::std::option::Option::Some(StatusCode::Succeed),
            1 => ::std::option::Option::Some(StatusCode::Failed),
            2 => ::std::option::Option::Some(StatusCode::Unauthorized),
            3 => ::std::option::Option::Some(StatusCode::NotFound),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [StatusCode] = &[
            StatusCode::Succeed,
            StatusCode::Failed,
            StatusCode::Unauthorized,
            StatusCode::NotFound,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::EnumDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new("StatusCode", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for StatusCode {
}

impl ::std::default::Default for StatusCode {
    fn default() -> Self {
        StatusCode::Succeed
    }
}

impl ::protobuf::reflect::ProtobufValue for StatusCode {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1edynamic_update_interface.proto\x12\x06client\x1a\x0brrset.proto\"L\
    \n\x0fAddRRsetRequest\x12\x12\n\x04zone\x18\x01\x20\x01(\tR\x04zone\x12%\
    \n\x06rrsets\x18\x02\x20\x03(\x0b2\r.client.RRsetR\x06rrsets\"T\n\x10Add\
    RRsetResponse\x12&\n\x04code\x18\x01\x20\x01(\x0e2\x12.client.StatusCode\
    R\x04code\x12\x18\n\x07message\x18\x02\x20\x01(\tR\x07message\"?\n\x13De\
    leteDomainRequest\x12\x12\n\x04zone\x18\x01\x20\x01(\tR\x04zone\x12\x14\
    \n\x05names\x18\x02\x20\x03(\tR\x05names\"X\n\x14DeleteDomainResponse\
    \x12&\n\x04code\x18\x01\x20\x01(\x0e2\x12.client.StatusCodeR\x04code\x12\
    \x18\n\x07message\x18\x02\x20\x01(\tR\x07message\"U\n\x12DeleteRRsetRequ\
    est\x12\x12\n\x04zone\x18\x01\x20\x01(\tR\x04zone\x12+\n\x06rrsets\x18\
    \x02\x20\x03(\x0b2\x13.client.RRsetHeaderR\x06rrsets\"W\n\x13DeleteRRset\
    Response\x12&\n\x04code\x18\x01\x20\x01(\x0e2\x12.client.StatusCodeR\x04\
    code\x12\x18\n\x07message\x18\x02\x20\x01(\tR\x07message\"O\n\x12DeleteR\
    dataRequest\x12\x12\n\x04zone\x18\x01\x20\x01(\tR\x04zone\x12%\n\x06rrse\
    ts\x18\x02\x20\x03(\x0b2\r.client.RRsetR\x06rrsets\"W\n\x13DeleteRdataRe\
    sponse\x12&\n\x04code\x18\x01\x20\x01(\x0e2\x12.client.StatusCodeR\x04co\
    de\x12\x18\n\x07message\x18\x02\x20\x01(\tR\x07message\"\x84\x01\n\x12Up\
    dateRdataRequest\x12\x12\n\x04zone\x18\x01\x20\x01(\tR\x04zone\x12,\n\no\
    ld_rrsets\x18\x02\x20\x03(\x0b2\r.client.RRsetR\toldRrsets\x12,\n\nnew_r\
    rsets\x18\x03\x20\x03(\x0b2\r.client.RRsetR\tnewRrsets\"W\n\x13UpdateRda\
    taResponse\x12&\n\x04code\x18\x01\x20\x01(\x0e2\x12.client.StatusCodeR\
    \x04code\x12\x18\n\x07message\x18\x02\x20\x01(\tR\x07message*E\n\nStatus\
    Code\x12\x0b\n\x07Succeed\x10\0\x12\n\n\x06Failed\x10\x01\x12\x10\n\x0cU\
    nauthorized\x10\x02\x12\x0c\n\x08NotFound\x10\x032\x84\x03\n\x16DynamicU\
    pdateInterface\x12?\n\x08AddRRset\x12\x17.client.AddRRsetRequest\x1a\x18\
    .client.AddRRsetResponse\"\0\x12K\n\x0cDeleteDomain\x12\x1b.client.Delet\
    eDomainRequest\x1a\x1c.client.DeleteDomainResponse\"\0\x12H\n\x0bDeleteR\
    Rset\x12\x1a.client.DeleteRRsetRequest\x1a\x1b.client.DeleteRRsetRespons\
    e\"\0\x12H\n\x0bDeleteRdata\x12\x1a.client.DeleteRdataRequest\x1a\x1b.cl\
    ient.DeleteRdataResponse\"\0\x12H\n\x0bUpdateRdata\x12\x1a.client.Update\
    RdataRequest\x1a\x1b.client.UpdateRdataResponse\"\0b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
